// GENERATED by scripts/fetch-sponsors.ts — do not edit by hand.
//
// Refresh locally with:  SPONSORS_TOKEN=<github PAT w/ read:user> bun run fetch:sponsors
// On Cloudflare Pages it refreshes on every deploy when SPONSORS_TOKEN is set
// (build:static runs the fetch first, falling back to this committed list).
//
// `monthlyDollars` is the sponsor's tier amount; the homepage buckets it into
// platinum / gold / silver / bronze sizes (see app/components/sponsors.tsx).

export interface Sponsor {
  login: string
  name: string | null
  avatarUrl: string
  url: string
  monthlyDollars: number
  oneTime: boolean
}

export const SPONSORS_UPDATED_AT: string | null = null

export const SPONSORS: Sponsor[] = []
