// GENERATED by scripts/fetch-sponsors.ts — do not edit by hand.
//
// Refresh locally with:  bun run fetch:sponsors  (uses your gh CLI token)
// On Cloudflare Pages it refreshes on every deploy when SPONSORS_TOKEN is set
// (build:static runs the fetch first, falling back to this committed list).
//
// `monthlyDollars` is the sponsor's tier amount; the homepage buckets it into
// platinum / gold / silver / bronze sizes (see app/components/sponsors.tsx).

export interface Sponsor {
  login: string
  name: string | null
  avatarUrl: string
  url: string
  monthlyDollars: number
  oneTime: boolean
}

export const SPONSORS_UPDATED_AT: string | null = "2026-06-03T06:56:10.751Z"

export const SPONSORS: Sponsor[] = [
  {"login":"ddloophq","name":"DDLoop HQ","avatarUrl":"https://avatars.githubusercontent.com/u/110884490?s=160&v=4","url":"https://github.com/ddloophq","monthlyDollars":50,"oneTime":false},
  {"login":"smtplabs","name":"Email Testing for Developers - SMTP Labs, Inc.","avatarUrl":"https://avatars.githubusercontent.com/u/89388475?s=160&v=4","url":"https://github.com/smtplabs","monthlyDollars":15,"oneTime":false},
  {"login":"receipting","name":"Receipting.com","avatarUrl":"https://avatars.githubusercontent.com/u/233199475?s=160&v=4","url":"https://github.com/receipting","monthlyDollars":0,"oneTime":false}
]
