#!/usr/bin/env bun
//
// Fetch the maintainer's GitHub Sponsors and regenerate app/data/sponsors.ts.
//
// Run it by hand whenever you want to refresh the homepage list:
//   bun run fetch:sponsors            (uses the gh CLI's token if logged in)
//   SPONSORS_TOKEN=<github PAT> bun run fetch:sponsors
//
// It also runs automatically before `build:static` (Cloudflare Pages). When no
// token is available — or the GitHub API errors — it leaves the committed
// app/data/sponsors.ts untouched and exits 0, so a deploy never breaks just
// because sponsors couldn't be fetched.
//
// Token resolution (first match wins):
//   SPONSORS_TOKEN > GITHUB_TOKEN > GH_TOKEN > `gh auth token`
// Any token authenticated as the maintainer works — the fields we read (tier
// amount + sponsor entity) need no extra scopes. We deliberately don't request
// the one-time-payment / privacy fields, which would require `read:user`.
// `sponsorshipsAsMaintainer` excludes private sponsors by default, so the list
// is public-only.

import { writeFile } from "node:fs/promises"
import { spawnSync } from "node:child_process"
import { resolve } from "node:path"

const OUT = resolve(import.meta.dir, "..", "app", "data", "sponsors.ts")
const GQL = "https://api.github.com/graphql"

interface Sponsor {
  login: string
  name: string | null
  avatarUrl: string
  url: string
  monthlyDollars: number
  oneTime: boolean
}

function resolveToken(): string | null {
  const fromEnv = process.env.SPONSORS_TOKEN || process.env.GITHUB_TOKEN || process.env.GH_TOKEN
  if (fromEnv) return fromEnv.trim()
  // Local convenience: borrow the gh CLI's token if it's installed and logged in.
  try {
    const r = spawnSync("gh", ["auth", "token"], { encoding: "utf8" })
    const tok = (r.stdout || "").trim()
    if (r.status === 0 && tok) return tok
  } catch {
    /* gh not installed — fall through */
  }
  return null
}

const QUERY = `
query($cursor: String) {
  viewer {
    login
    sponsorshipsAsMaintainer(first: 100, after: $cursor, activeOnly: true, orderBy: {field: CREATED_AT, direction: DESC}) {
      totalCount
      pageInfo { hasNextPage endCursor }
      nodes {
        tier { monthlyPriceInDollars }
        sponsorEntity {
          __typename
          ... on User { login name avatarUrl(size: 160) url }
          ... on Organization { login name avatarUrl(size: 160) url }
        }
      }
    }
  }
}`

async function fetchSponsors(token: string): Promise<Sponsor[]> {
  const sponsors: Sponsor[] = []
  let cursor: string | null = null
  for (;;) {
    const res = await fetch(GQL, {
      method: "POST",
      headers: {
        Authorization: `bearer ${token}`,
        "Content-Type": "application/json",
        "User-Agent": "shadcn-htmx-sponsors",
      },
      body: JSON.stringify({ query: QUERY, variables: { cursor } }),
    })
    const json: any = await res.json()
    if (json.errors?.length) {
      const scope = json.errors.find((e: any) => e.type === "INSUFFICIENT_SCOPES")
      if (scope) {
        throw new Error("token is missing the `read:user` scope required for the Sponsors API")
      }
      throw new Error(json.errors.map((e: any) => e.message).join("; "))
    }
    const conn = json.data?.viewer?.sponsorshipsAsMaintainer
    if (!conn) throw new Error("unexpected API response (no sponsorshipsAsMaintainer)")
    for (const node of conn.nodes ?? []) {
      const e = node.sponsorEntity
      if (!e?.login) continue // private sponsor with no exposed entity — skip
      sponsors.push({
        login: e.login,
        name: e.name ?? null,
        avatarUrl: e.avatarUrl,
        url: e.url,
        monthlyDollars: node.tier?.monthlyPriceInDollars ?? 0,
        oneTime: false, // not requested — needs read:user; unused by the homepage
      })
    }
    if (!conn.pageInfo?.hasNextPage) break
    cursor = conn.pageInfo.endCursor
  }
  // Highest tier first, then alphabetical for stable output.
  sponsors.sort((a, b) => b.monthlyDollars - a.monthlyDollars || a.login.localeCompare(b.login))
  return sponsors
}

function render(sponsors: Sponsor[], updatedAt: string): string {
  const list = sponsors.map((s) => "  " + JSON.stringify(s)).join(",\n")
  return `// GENERATED by scripts/fetch-sponsors.ts — do not edit by hand.
//
// Refresh locally with:  bun run fetch:sponsors  (uses your gh CLI token)
// On Cloudflare Pages it refreshes on every deploy when SPONSORS_TOKEN is set
// (build:static runs the fetch first, falling back to this committed list).
//
// \`monthlyDollars\` is the sponsor's tier amount; the homepage buckets it into
// platinum / gold / silver / bronze sizes (see app/components/sponsors.tsx).

export interface Sponsor {
  login: string
  name: string | null
  avatarUrl: string
  url: string
  monthlyDollars: number
  oneTime: boolean
}

export const SPONSORS_UPDATED_AT: string | null = ${JSON.stringify(updatedAt)}

export const SPONSORS: Sponsor[] = [
${list}${list ? "\n" : ""}]
`
}

async function main() {
  const token = resolveToken()
  if (!token) {
    console.warn(
      "! fetch-sponsors: no token (set SPONSORS_TOKEN with a read:user PAT). " +
        "Keeping the committed app/data/sponsors.ts.",
    )
    return
  }
  let sponsors: Sponsor[]
  try {
    sponsors = await fetchSponsors(token)
  } catch (e) {
    console.warn(`! fetch-sponsors: ${(e as Error).message}. Keeping the committed app/data/sponsors.ts.`)
    return
  }
  await writeFile(OUT, render(sponsors, new Date().toISOString()))
  const byTier = (min: number, max: number) => sponsors.filter((s) => s.monthlyDollars >= min && s.monthlyDollars < max).length
  console.log(
    `✓ fetch-sponsors: wrote ${sponsors.length} sponsor(s) → app/data/sponsors.ts ` +
      `(platinum ${byTier(50, Infinity)}, gold ${byTier(20, 50)}, silver ${byTier(10, 20)}, bronze ${byTier(0, 10)})`,
  )
}

// Never fail the build over sponsor fetching — warn and keep the committed list.
main().catch((e) => {
  console.warn(`! fetch-sponsors: unexpected error: ${e?.message ?? e}. Keeping the committed app/data/sponsors.ts.`)
})
